apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/frontend

namespace: blog-dev

replicas:
  - name: frontend
    count: 1

images:
  - name: 01791689522/blog-frontend
    newTag: 1.2.0
