apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/redis

namespace: blog-dev

replicas:
  - name: redis
    count: 1

images:
  - name: redis
    newTag: 7.4.1
