apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/ingress

namespace: blog-dev

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: blog-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-blog.local.com
