apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../apps/mongodb

namespace: blog-dev

replicas:
  - name: mongodb
    count: 1

images:
  - name: mongo
    newTag: "7.0"
